### ISSUE TITLE
Is jpegli enabled and how to enable if not?

### ISSUE THREAD

**Issue by jobpaardekooper** [gen2brain/jpegxl#2]
Hello, I was wondering if `jpegli` is enabled in the pre-compiled WASM build.  For example, `Makefile.encode` does reference `jpegli.cmake` and has `DJPEGXL_ENABLE_JPEGLI=0` and `DJPEGXL_ENABLE_JPEGLI_LIBJPEG=0` so I would assume `jpegli` is not on by default.

When I set `DJPEGXL_ENABLE_JPEGLI=1` and `DJPEGXL_ENABLE_JPEGLI_LIBJPEG=1` the code compiles and it seems to do something with jpegli but the size of the resulting `encode.wasm` is the same so I am wondering if it really gets compiled in. Is there a way to tell how?

Thanks for the effort with making this code available.

**Comment by jobpaardekooper** [comment]
I just tested with building a `.wasm` file with both configurations and encoding an image with that. The resulting file sizes were exactly the same so I think using these options does not make a difference.

@gen2brain Maybe you have some insight on this?

**Comment by gen2brain** [comment]
Not sure, but I think that `jpegli` is used only when encoding, and only with `JxlEncoderAddJPEGFrame`, i.e. see https://github.com/libjxl/libjxl/blob/main/lib/include/jxl/encode.h#L628, as this is not used here it is disabled. `cjxl` use it when you want to directly encode jpeg to jxl.

If you are only interested in `jpegli` I have a repo here https://github.com/gen2brain/jpegli, and it does make a difference in file size.

**Comment by gen2brain** [comment]
Btw. the size of the binary `encode.wasm` is the same probably because it is not used, if/when C code would use `JxlEncoderAddJPEGFrame` the size would be larger.
I thought about adding a new function, something like `EncodeJPEG`, then to check if the data passed is a JPEG, etc., and use `JxlEncoderAddJPEGFrame` and `JxlEncoderStoreJPEGMetadata` to losslessly reconstruct the JPEG codestream, but I don't have the time and I lost interest, and kinda disappointed that `jxl` will not be included in browsers.

**Comment by jobpaardekooper** [comment]
Thanks for the quick and detailed response!

I am sure I found your jpegli repo a few days ago and briefly took a look. Then when I actually started working on it I only found this one and thought I might have confused something😅 Weird how google is not ranking these repos very well.

Thanks for linking the other repo. I will continue with that.
